### PR TITLE
fix: player does not spasm into walls

### LINKED ISSUE #7: Running into a wall causes the player to spasm

### LINKED ISSUE #15: Player cannot jump when near edge

### PR DESCRIPTION
**Pull request by Rinder5**
fixes #15 and fixes #7 

introduces a new bug where the player stops moving randomly. This is because the raycasts are stupidly made and will run into the floor and into other stuff when they are not supposed to.

### CODE REVIEW

File: Assets/Scripts/PlayerController.cs [hunk 1]
```diff
@@ -12,16 +12,73 @@ public class PlayerController : MonoBehaviour
...
 
     // Use this for initialization
     private void Start()
     {
         _rb = GetComponent<Rigidbody>();
+        _heading = Vector3.forward;
+        groundSkinVertices[0] = Vector3.zero - (Vector3.right * Bc.bounds.extents.x) - (Vector3.forward * Bc.bounds.extents.z);
+        groundSkinVertices[1] = Vector3.zero - (Vector3.right * Bc.bounds.extents.x) + (Vector3.forward * Bc.bounds.extents.z);
+        groundSkinVertices[2] = Vector3.zero + (Vector3.right * Bc.bounds.extents.x) + (Vector3.forward * Bc.bounds.extents.z);
+        groundSkinVertices[3] = Vector3.zero + (Vector3.right * Bc.bounds.extents.x) - (Vector3.forward * Bc.bounds.extents.z);
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: this can be changed to 
`Vector3(Bc.bounds.extents.x, 0, -Bc.bounds.extents.z)`

Same for the rest.

File: Assets/Scripts/PlayerController.cs [hunk 2]
```diff
@@ -12,16 +12,73 @@ public class PlayerController : MonoBehaviour
...
+                groundSkinVertices[(j-1) + 4 + (3 * i)] = new Vector3(xStart + ((xDiff / 4) * j),
+                    0,
+                    zStart + ((zDiff / 4) * j));
+            }
+        }
 
+        forwardSkinVertices[0] = Vector3.zero - (Vector3.right * Bc.bounds.extents.x) - (Vector3.up * (Bc.bounds.extents.y - 0.1f)) + (Vector3.forward * Bc.bounds.extents.z);
+        forwardSkinVertices[1] = Vector3.zero - (Vector3.right * Bc.bounds.extents.x) + (Vector3.up * (Bc.bounds.extents.y - 0.1f)) + (Vector3.forward * Bc.bounds.extents.z);
+        forwardSkinVertices[2] = Vector3.zero + (Vector3.right * Bc.bounds.extents.x) + (Vector3.up * (Bc.bounds.extents.y - 0.1f)) + (Vector3.forward * Bc.bounds.extents.z);
+        forwardSkinVertices[3] = Vector3.zero + (Vector3.right * Bc.bounds.extents.x) - (Vector3.up * (Bc.bounds.extents.y - 0.1f)) + (Vector3.forward * Bc.bounds.extents.z);
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: same here

**Comment by Rinder5** [comment]
@nicholaschuayunzhi for your review

File: Assets/Scripts/PlayerController.cs [hunk 3]
```diff
@@ -63,7 +91,7 @@ public void UpdateCamera()
     // Update is called once per frame
     private void Update()
     {
-        if (Input.GetAxis("Horizontal") != 0 || Input.GetAxis("Vertical") != 0)
+        if (Mathf.Abs(Input.GetAxis("Horizontal")) == 1 || Mathf.Abs(Input.GetAxis("Vertical")) == 1)
         {
             Move();
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs:84]: Was this changed to remove minor movements which cause the spasms?

File: Assets/Scripts/PlayerController.cs [hunk 4]
```diff
@@ -41,16 +68,16 @@ private void Update()
...
         }
 
-        if (_onGround && Input.GetAxis("Jump") == 1.0f)
+        if (Input.GetAxis("Jump") == 1.0f)
         {
-            Jump();
+            if (IsOnGround())
+                Jump();
         }
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: Any reason in particular for separating the this from the if statement above? I think it would be better to have it in the one line to reduce nesting.

File: Assets/Scripts/PlayerController.cs [hunk 5]
```diff
@@ -1,26 +1,53 @@
...
+        for (int i = 0; i < 4; i++)
+        {
+            float xDiff;
+            float zDiff;
+            if (i < 3)
+            {
+                xDiff = groundSkinVertices[i + 1].x - groundSkinVertices[i].x;
+                zDiff = groundSkinVertices[i + 1].z - groundSkinVertices[i].z;
+            }
+            else
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: can simplify to 
```cs
xDiff = groundSkinVertices[(i + 1) % 3].x - groundSkinVertices[i].x;
zDiff = groundSkinVertices[(i + 1) % 3].z - groundSkinVertices[i].z;
```

Could get `(i + 1) % 3` into a variable first too.

File: Assets/Scripts/PlayerController.cs [hunk 6]
```diff
@@ -1,26 +1,53 @@
...
 
     private Vector3 _forward;
     private Vector3 _right;
-
-    private bool _onGround = true;
+    private Vector3 _heading;
 
     private Rigidbody _rb;
+    public BoxCollider Bc;
+    private Vector3[] groundSkinVertices = new Vector3[40];
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: Not too sure myself but must you place leading underscore for this?

File: Assets/Scripts/PlayerController.cs [hunk 7]
```diff
@@ -1,26 +1,53 @@
...
+            else
+            {
+                xDiff = groundSkinVertices[0].x - groundSkinVertices[i].x;
+                zDiff = groundSkinVertices[0].z - groundSkinVertices[i].z;
+            }
+            float zStart = groundSkinVertices[i].z;
+            float xStart = groundSkinVertices[i].x;
+            for (int j = 1; j < 10; j++)
+            {
+                groundSkinVertices[(j-1) + 4 + (9 * i)] = new Vector3(xStart + ((xDiff / 9) * j),
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: could we start with
```cs
 for (int j = 0; j < 9; j++)
```
to get 
```cs
groundSkinVertices[j + 4 + (9 * i)]
```

File: Assets/Scripts/PlayerController.cs [hunk 8]
```diff
@@ -1,27 +1,82 @@
...
+        forwardSkinVertices[2] = new Vector3(0, -(Bc.bounds.extents.y - 0.01f), -(Bc.bounds.extents.z - 0.1f));
+        forwardSkinVertices[3] = new Vector3(0, -(Bc.bounds.extents.y - 0.01f), Bc.bounds.extents.z - 0.1f);
+        for (int i = 0; i < 4; i++)
+        {
+            float yDiff;
+            float zDiff;
+            if (i < 3)
+            {
+                yDiff = forwardSkinVertices[i + 1].y - forwardSkinVertices[i].y;
+                zDiff = forwardSkinVertices[i + 1].z - forwardSkinVertices[i].z;
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: Same as: https://github.com/this-place/this.place/pull/29/files#r171890298

File: Assets/Scripts/PlayerController.cs [hunk 9]
```diff
@@ -1,27 +1,82 @@
...
+                yDiff = forwardSkinVertices[0].y - forwardSkinVertices[i].y;
+                zDiff = forwardSkinVertices[0].z - forwardSkinVertices[i].z;
+            }
+            float yStart = forwardSkinVertices[i].y;
+            float zStart = forwardSkinVertices[i].z;
+            for (int j = 1; j < 4; j++)
+            {
+                forwardSkinVertices[(j - 1) + 4 + (3 * i)] = new Vector3(0,
+                    yStart + ((yDiff / 4) * j),
+                    zStart + ((zDiff / 4) * j));
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: Same as: https://github.com/this-place/this.place/pull/29/files#r171892065

File: Assets/Scripts/PlayerController.cs (hunk 7 above)
Comment (nicholaschuayunzhi) [reply Assets/Scripts/PlayerController.cs]: Also is there a better way to format the `Vector3` constructor?

File: Assets/Scripts/PlayerController.cs [hunk 10]
```diff
@@ -1,27 +1,82 @@
...
 
     // Use this for initialization
     private void Start()
     {
         _rb = GetComponent<Rigidbody>();
+        _heading = Vector3.forward;
+        groundSkinVertices[0] = new Vector3(Bc.bounds.extents.x - 0.05f, 0, Bc.bounds.extents.z - 0.05f);
+        groundSkinVertices[1] = new Vector3(Bc.bounds.extents.x - 0.05f, 0, -(Bc.bounds.extents.z - 0.05f));
+        groundSkinVertices[2] = new Vector3(-(Bc.bounds.extents.x - 0.05f), 0, -(Bc.bounds.extents.z - 0.05f));
+        groundSkinVertices[3] = new Vector3(-(Bc.bounds.extents.x - 0.05f), 0, Bc.bounds.extents.z - 0.05f);
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: what does `0.05f` mean and is is the same idea as the `forwardSkinVertices` `0.01f`? Are we able to combine them into a  single variable?

**Review by nicholaschuayunzhi — COMMENTED** [review]
Hi @Rinder5, thanks for your hard work! This is not an easy fix and I have a few small nits with the code. Left a few comments for your reference

File: Assets/Scripts/PlayerController.cs (hunk 3 above)
Comment (Rinder5) [reply Assets/Scripts/PlayerController.cs:84]: its for removing the character slowly rotating by itself when you let go of buttons. makes it so that when next to a wall, the character doesn't sometimes push itself back by turning

File: Assets/Scripts/PlayerController.cs (hunk 4 above)
Comment (Rinder5) [reply Assets/Scripts/PlayerController.cs]: can also. i was thinking it's better to separate, because the input is a player action, while isonground is not, so to me they feel like putting them together feels a bit weird

File: Assets/Scripts/PlayerController.cs (hunk 10 above)
Comment (Rinder5) [reply Assets/Scripts/PlayerController.cs]: yup, same idea. don't know if we can combine them because we might want different values for them

File: Assets/Scripts/PlayerController.cs (hunk 3 above)
Comment (Rinder5) [reply Assets/Scripts/PlayerController.cs:84]: actually, I should mention that the new implementation is that in addition to stopping when running straight into a wall, when running into a wall at an angle, the player will now run alongside the wall.

**Review by nicholaschuayunzhi — APPROVED** [review]
