### PR TITLE
fix: blocks bound by gravity are no longer top displaceable

### LINKED ISSUE #119: Blocks bound by gravity should not be top displaceable

### PR DESCRIPTION
**Pull request by reginleiff**
Fixes #119. Merge #126 before this.

Doesn't remove highlights from disintegrate block for some reason, despite the fix working for sand.

### CODE REVIEW

File: Assets/Scripts/BlockBehaviour.cs [hunk 1]
```diff
@@ -195,4 +196,14 @@ public void PlayDisplacementSound()
...
     }
+
+    public void SetBoundByGravity()
+    {
+        _boundByGravity = true;
+    }
+
+    public bool IsBoundByGravity()
+    {
+        return _boundByGravity;
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/BlockBehaviour.cs:207]: I think we should not have information about gravity for each block. Rather lets change `Moveable` to give us the flexibility to on what faces we can actually interact with. This way we don't need all these getters as well.

**Review by nicholaschuayunzhi — COMMENTED** [review]
You can wait for my refactoring as I'm going to remove the `IDisplaceable` interface. But do let me know if my suggestion to make `Moveable` expose more options feasible and if you faced any problems regarding this.

Also let me know how you think it should behave.
