### PR TITLE
Fix: player doesn't jump when touching wall

### LINKED ISSUE #6: Player can jump after touching a wall

### PR DESCRIPTION
**Pull request by Rinder5**
fixes #6

### CODE REVIEW

File: Assets/Scripts/PlayerController.cs [hunk 1]
```diff
@@ -8,6 +8,7 @@ public class PlayerController : MonoBehaviour
     [SerializeField]
     private const float MoveSpeed = 2f;
     private const float JumpForce = 5.2f;
+    private const float DistToGround = 1.0f;
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs:11]: is this the distance from player transform to ground?

Comment (Rinder5) [reply Assets/Scripts/PlayerController.cs:11]: from the draggy thingy to the ground, yes.
