### PR TITLE
fix: look rotation vector error no longer displays

### LINKED ISSUE #11: Fix 'Look rotation viewing vector is zero' error message in console log

### PR DESCRIPTION
**Pull request by Rinder5**
fixes #11

### CODE REVIEW

File: Assets/Scripts/PlayerController.cs [hunk 1]
```diff
@@ -44,8 +44,8 @@ private void Move()
         Vector3 upMovement = _forward * MoveSpeed * Time.deltaTime * Input.GetAxis("Vertical");
 
         Vector3 heading = Vector3.Normalize(rightMovement + upMovement);
-
-        transform.forward = heading;
+        if (Input.GetAxis("Horizontal") != 0 || Input.GetAxis("Vertical") != 0)
+            transform.forward = heading;
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: Could you check whether the heading is `Vector3.zero` instead? If we decide to refactor our Input system, we will have to touch this as well.

File: Assets/Scripts/PlayerController.cs [hunk 2]
```diff
@@ -32,29 +32,35 @@ private void Update()
     {
         if (Input.anyKey)
         {
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: Could we remove this Input.anyKey, seems to add unnecessary nested blocks.

File: Assets/Scripts/PlayerController.cs [hunk 3]
```diff
@@ -32,29 +32,35 @@ private void Update()
...
     private void Move()
     {
-
         Vector3 direction = new Vector3(Input.GetAxis("Horizontal"), 0, Input.GetAxis("Vertical"));
         Vector3 rightMovement = _right * MoveSpeed * Time.deltaTime * Input.GetAxis("Horizontal");
         Vector3 upMovement = _forward * MoveSpeed * Time.deltaTime * Input.GetAxis("Vertical");
 
         Vector3 heading = Vector3.Normalize(rightMovement + upMovement);
-
+
```
Comment (nicholaschuayunzhi) [inline Assets/Scripts/PlayerController.cs]: Remove trailing whitespace

File: Assets/Scripts/PlayerController.cs (hunk 2 above)
Comment (Rinder5) [reply Assets/Scripts/PlayerController.cs]: it makes sure that things only happen if a button is pressed. Otherwise, GetAxis("Horizontal") and "Vertical" slowly revert to neutral, changing the player facing back to normal as well.

Comment (nicholaschuayunzhi) [reply Assets/Scripts/PlayerController.cs]: Hmm good point. Maybe we can use `Input.GetAxisRaw` instead, (i've tried locally, seems to be fine, let me know if i missed something). So we don't have the smoothing. Also could you change `e07d15e` to `style:`
